### PR TITLE
Use logging

### LINKED ISSUE #12: PyFMI prints stuff to stdout
PyFMI outputs simulation times to the console.

```
Elapsed simulation time: 0.35966514999745414 seconds.
Simulation interval    : 0.0 - 0.0 seconds.
Elapsed simulation time: 0.1477236869977787 seconds.
Simulation interval    : 0.0 - 0.0 seconds.
Elapsed simulation time: 0.14188759902026504 seconds.
...
```

This is not desirable for a library, see https://fangpenlin.com/posts/2012/08/26/good-logging-practice-in-python/

### PR DESCRIPTION
**Pull request by jschueller**
Partially adresses #12, they may be more "print" to replace by logging calls

### CODE REVIEW

**Comment by jschueller** [comment]
Hello @chria can you have a look a this one ?
(And please avoid force-push to public master again, this makes everyone go out of sync)

**Comment by chria** [comment]
Hi, sorry about the force push. I'll have a look at it.

**Comment by jschueller** [comment]
@chria could look at this for next release please ?

**Comment by chria** [comment]
Yes, sorry. I'll look at it for the next release

**Comment by chria** [comment]
Just a quick question, would it be sufficient to introduce a simulation option "verbosity" that determines how much output is shown?

**Comment by jschueller** [comment]
yes, that works too

**Comment by jschueller** [comment]
hello @chria @christian-winther could this be looked into for the next release ?

**Comment by chria** [comment]
Hi, sorry about the delay. I introduced another option in https://github.com/modelon-community/PyFMI/commit/df8228d4d97cfde3cd3fc321a4f3da31b417d4be

**Comment by jschueller** [comment]
ok, how do I use this function from the high level apis ?

**Comment by chria** [comment]
Hi,

`model = load_fmu(".....")`
`opts = model.simulate_options()`
`opts["silent_mode"] = True`
`res = model.simulate(options=opts)`

Best
/Christian

**Comment by jschueller** [comment]
ok, thanks

**Pull request closed without merging**
